### ISSUE TITLE
MATLAB view_marking error

### ISSUE THREAD

**Issue by MatthewPool256** [soltanianzadeh/STNeuroNet#3]
When running view_marking on Neurofinder 100 train with neurofinder marking, I eventually get an error from line 21 round(CC.Centroid) in RemoveNeuropil.m. From the debugger, this is because the struct at this time (when k=322) is empty. Likewise, temp is an array of all zeros at this time, which I believe is what causes CC to be empty. I do not know why this happens, but it is preventing the code from running properly. Any help would be appreciated.

**Comment by soltanianzadeh** [comment]
@MatthewPool256 Thanks for reporting this issue. I have made minor edits to the ViewNeuronMarking.m code to prevent this issue. As you mentioned, the error was caused due to the presence of an all zero mask in the neurofinder marking. This all zero mask was most likely created when the borders of the masks were cropped and saved in the .mat file. 

In general, it is best to avoid saving such masks (all zero pixels) as the FInalMasks.

**Comment by MatthewPool256** [comment]
With the new files (and after installing the MATLAB GUI Layout Toolbox) I was able to run view_marking.m properly, thank you.
